version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: mcprism
      POSTGRES_PASSWORD: mcprism_dev
      POSTGRES_DB: mcprism
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcprism"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Gateway service (uncomment when ready)
  # gateway:
  #   build:
  #     context: .
  #     dockerfile: apps/gateway/Dockerfile
  #   environment:
  #     DATABASE_URL: postgresql://mcprism:mcprism_dev@postgres:5432/mcprism
  #     PORT: 3001
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
